launch_buttons:
  binderhub_url: "https://hub.2i2c.mybinder.org/user/trefftzc-exploringhaskell-ey2scspv/doc/tree/FirstHaskellNotebook.ipynb"  # The URL for your BinderHub (e.g., https://mybinder.org)
